spring:
  profiles:
    active:
      - dev
---
server:
  port: 8200
spring:
  application:
    name: SF-SERVER-DEV
  profiles: dev #开发环境
---
server:
  port: 8300
spring:
  application:
    name: SF-SERVER-TEST
  profiles: test #测试环境
